services:
  backup-vps:
    build: .
    restart: unless-stopped

    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?AWS_ACCESS_KEY_ID is required}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?AWS_SECRET_ACCESS_KEY is required}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD:?RESTIC_PASSWORD is required}

    volumes:
      - /opt/backups/logs:/logs

      - /opt/actual-budget:/sources/actual-budget:ro
      - /opt/invoiceshelf:/sources/invoiceshelf:ro
      - /opt/meshcentral:/sources/meshcentral:ro
      - /opt/outline:/sources/outline:ro
      - /opt/vaultwarden:/sources/vaultwarden:ro
      - /opt/tax-report-api:/sources/tax-report-api
      - /opt/time-tracking-api:/sources/time-tracking-api:ro

