services:
  backup-vps:
    build: .
    restart: unless-stopped

    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?AWS_ACCESS_KEY_ID is required}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?AWS_SECRET_ACCESS_KEY is required}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD:?RESTIC_PASSWORD is required}

    volumes:
      - /opt/backups/logs:/logs
      - /data/coolify/backups/databases/root-team-0/tax-report-mysql-sc4mzxajrw40ce62k4neogvn:/sources/tax-report-mysql:ro
      - /data/coolify/backups/databases/root-team-0/time-tracking-postgres-onniddcgq2o44zz3r6hkvroy:/sources/time-tracking-postgres:ro
      - /opt/docker/vaultwarden/data:/sources/vaultwarden:ro

